URL = https://demoqa.com/

#MYSQL DB Properties
MYSQLhost =
MYSQLport =
MYSQLuser =
MYSQLpassword =

#WINSCP/Putty Connection Properties
SFTPPuser =
SFTPPassword =
SFTPhost =
SFTPport=
moduleNameRowCountForExcel = 1
testResultsFileRowCountForExcel = 1
emailAddressRowCountForExcel = 1
moduleName = Element Test
testResultsFileName = Admin ExtentReport_Element Test.html
